import { MemberRecord } from "../types";

export const SEED_MEMBERS: MemberRecord[] = [
  {
    id: "usr-001",
    nama: "Ardy Syafii",
    no_kta: "DRG-2026-001",
    no_hp: "081234567890",
    pangkalan: "Pangkalan Suhat",
    role: "super_admin",
    jenjang: "Utama",
    status: "aktif",
    bergabung_sejak: "01 Oktober 2026",
    plat_nomor: "N 1234 AB",
    jenis_kendaraan: "Honda Vario 160",
    email: "ardy.syafii@gmail.com",
    catatan: "Koordinator Utama & Pengawas Sistem DRG",
  },
  {
    id: "usr-002",
    nama: "Bambang Pamungkas",
    no_kta: "DRG-2026-002",
    no_hp: "081234567891",
    pangkalan: "Pangkalan Suhat",
    role: "ketua",
    jenjang: "Utama",
    status: "aktif",
    bergabung_sejak: "05 Oktober 2026",
    plat_nomor: "N 2345 BC",
    jenis_kendaraan: "Yamaha NMAX 155",
    email: "bambang.p@driver-drg.org",
    catatan: "Ketua Umum Komunitas DRG periode 2026-2028",
  },
  {
    id: "usr-003",
    nama: "Cahyo Wibowo",
    no_kta: "DRG-2026-003",
    no_hp: "081234567892",
    pangkalan: "Pangkalan Dinoyo",
    role: "satgas",
    jenjang: "Madya",
    status: "aktif",
    bergabung_sejak: "12 Oktober 2026",
    plat_nomor: "N 3456 CD",
    jenis_kendaraan: "Honda PCX 160",
    catatan: "Tim Satgas Reaksi Cepat Lapangan Dinoyo",
  },
  {
    id: "usr-004",
    nama: "Dedi Prasetyo",
    no_kta: "DRG-2026-004",
    no_hp: "081234567893",
    pangkalan: "Pangkalan Sawojajar",
    role: "driver",
    jenjang: "Pratama",
    status: "pending_review",
    bergabung_sejak: "02 November 2026",
    plat_nomor: "N 4567 DE",
    jenis_kendaraan: "Honda Beat Street",
    catatan: "Pendaftaran baru via Korlap Sawojajar - Dokumen KTP terlampir",
  },
  {
    id: "usr-005",
    nama: "Eko Wahyudi",
    no_kta: "DRG-2026-005",
    no_hp: "081234567894",
    pangkalan: "Pangkalan Sulfat",
    role: "korlap",
    jenjang: "Madya",
    status: "aktif",
    bergabung_sejak: "18 Oktober 2026",
    plat_nomor: "N 5678 EF",
    jenis_kendaraan: "Yamaha Aerox 155",
    catatan: "Koordinator Lapangan Area Sulfat & Blimbing",
  },
  {
    id: "usr-006",
    nama: "Fajar Nugraha",
    no_kta: "DRG-2026-006",
    no_hp: "081234567895",
    pangkalan: "Pangkalan Dinoyo",
    role: "driver",
    jenjang: "Pratama",
    status: "pending_review",
    bergabung_sejak: "03 November 2026",
    plat_nomor: "N 6789 FG",
    jenis_kendaraan: "Honda Scoopy 2024",
    catatan: "Menunggu verifikasi SIM C & STNK oleh admin",
  },
  {
    id: "usr-007",
    nama: "Gunawan Santoso",
    no_kta: "DRG-2026-007",
    no_hp: "081234567896",
    pangkalan: "Pangkalan Sawojajar",
    role: "bendahara",
    jenjang: "Utama",
    status: "aktif",
    bergabung_sejak: "08 Oktober 2026",
    plat_nomor: "N 7890 GH",
    jenis_kendaraan: "Honda Vario 125",
    catatan: "Bendahara Kas Gotong Royong DRG",
  },
  {
    id: "usr-008",
    nama: "Hendra Kurniawan",
    no_kta: "DRG-2026-008",
    no_hp: "081234567897",
    pangkalan: "Pangkalan Suhat",
    role: "driver",
    jenjang: "Pratama",
    status: "aktif",
    bergabung_sejak: "25 Oktober 2026",
    plat_nomor: "N 8901 HI",
    jenis_kendaraan: "Yamaha Jupiter MX King",
    catatan: "Driver aktif pangkalan Suhat",
  },
];
