/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiAuthRouteImport } from './routes/api.auth'
import { Route as AuthenticatedScreeningRouteImport } from './routes/_authenticated/screening'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedPiketRouteImport } from './routes/_authenticated/piket'
import { Route as AuthenticatedPetaRouteImport } from './routes/_authenticated/peta'
import { Route as AuthenticatedPersetujuanRouteImport } from './routes/_authenticated/persetujuan'
import { Route as AuthenticatedPengaturanRouteImport } from './routes/_authenticated/pengaturan'
import { Route as AuthenticatedNotulenRouteImport } from './routes/_authenticated/notulen'
import { Route as AuthenticatedKejadianRouteImport } from './routes/_authenticated/kejadian'
import { Route as AuthenticatedKasRouteImport } from './routes/_authenticated/kas'
import { Route as AuthenticatedKaderisasiRouteImport } from './routes/_authenticated/kaderisasi'
import { Route as AuthenticatedInventarisRouteImport } from './routes/_authenticated/inventaris'
import { Route as AuthenticatedEtikRouteImport } from './routes/_authenticated/etik'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnggotaRouteImport } from './routes/_authenticated/anggota'
import { Route as AuthenticatedActivityLogRouteImport } from './routes/_authenticated/activity-log'

const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScreeningRoute = AuthenticatedScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPiketRoute = AuthenticatedPiketRouteImport.update({
  id: '/piket',
  path: '/piket',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPetaRoute = AuthenticatedPetaRouteImport.update({
  id: '/peta',
  path: '/peta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersetujuanRoute =
  AuthenticatedPersetujuanRouteImport.update({
    id: '/persetujuan',
    path: '/persetujuan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPengaturanRoute = AuthenticatedPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotulenRoute = AuthenticatedNotulenRouteImport.update({
  id: '/notulen',
  path: '/notulen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKejadianRoute = AuthenticatedKejadianRouteImport.update({
  id: '/kejadian',
  path: '/kejadian',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKasRoute = AuthenticatedKasRouteImport.update({
  id: '/kas',
  path: '/kas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKaderisasiRoute = AuthenticatedKaderisasiRouteImport.update({
  id: '/kaderisasi',
  path: '/kaderisasi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventarisRoute = AuthenticatedInventarisRouteImport.update({
  id: '/inventaris',
  path: '/inventaris',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEtikRoute = AuthenticatedEtikRouteImport.update({
  id: '/etik',
  path: '/etik',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnggotaRoute = AuthenticatedAnggotaRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityLogRoute =
  AuthenticatedActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/daftar': typeof DaftarRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/anggota': typeof AuthenticatedAnggotaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/etik': typeof AuthenticatedEtikRoute
  '/inventaris': typeof AuthenticatedInventarisRoute
  '/kaderisasi': typeof AuthenticatedKaderisasiRoute
  '/kas': typeof AuthenticatedKasRoute
  '/kejadian': typeof AuthenticatedKejadianRoute
  '/notulen': typeof AuthenticatedNotulenRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/persetujuan': typeof AuthenticatedPersetujuanRoute
  '/peta': typeof AuthenticatedPetaRoute
  '/piket': typeof AuthenticatedPiketRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/screening': typeof AuthenticatedScreeningRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/daftar': typeof DaftarRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/anggota': typeof AuthenticatedAnggotaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/etik': typeof AuthenticatedEtikRoute
  '/inventaris': typeof AuthenticatedInventarisRoute
  '/kaderisasi': typeof AuthenticatedKaderisasiRoute
  '/kas': typeof AuthenticatedKasRoute
  '/kejadian': typeof AuthenticatedKejadianRoute
  '/notulen': typeof AuthenticatedNotulenRoute
  '/pengaturan': typeof AuthenticatedPengaturanRoute
  '/persetujuan': typeof AuthenticatedPersetujuanRoute
  '/peta': typeof AuthenticatedPetaRoute
  '/piket': typeof AuthenticatedPiketRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/screening': typeof AuthenticatedScreeningRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/daftar': typeof DaftarRoute
  '/_authenticated/activity-log': typeof AuthenticatedActivityLogRoute
  '/_authenticated/anggota': typeof AuthenticatedAnggotaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/etik': typeof AuthenticatedEtikRoute
  '/_authenticated/inventaris': typeof AuthenticatedInventarisRoute
  '/_authenticated/kaderisasi': typeof AuthenticatedKaderisasiRoute
  '/_authenticated/kas': typeof AuthenticatedKasRoute
  '/_authenticated/kejadian': typeof AuthenticatedKejadianRoute
  '/_authenticated/notulen': typeof AuthenticatedNotulenRoute
  '/_authenticated/pengaturan': typeof AuthenticatedPengaturanRoute
  '/_authenticated/persetujuan': typeof AuthenticatedPersetujuanRoute
  '/_authenticated/peta': typeof AuthenticatedPetaRoute
  '/_authenticated/piket': typeof AuthenticatedPiketRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/screening': typeof AuthenticatedScreeningRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/health': typeof ApiHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/daftar'
    | '/activity-log'
    | '/anggota'
    | '/dashboard'
    | '/etik'
    | '/inventaris'
    | '/kaderisasi'
    | '/kas'
    | '/kejadian'
    | '/notulen'
    | '/pengaturan'
    | '/persetujuan'
    | '/peta'
    | '/piket'
    | '/profil'
    | '/roles'
    | '/screening'
    | '/api/auth'
    | '/api/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/daftar'
    | '/activity-log'
    | '/anggota'
    | '/dashboard'
    | '/etik'
    | '/inventaris'
    | '/kaderisasi'
    | '/kas'
    | '/kejadian'
    | '/notulen'
    | '/pengaturan'
    | '/persetujuan'
    | '/peta'
    | '/piket'
    | '/profil'
    | '/roles'
    | '/screening'
    | '/api/auth'
    | '/api/health'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/daftar'
    | '/_authenticated/activity-log'
    | '/_authenticated/anggota'
    | '/_authenticated/dashboard'
    | '/_authenticated/etik'
    | '/_authenticated/inventaris'
    | '/_authenticated/kaderisasi'
    | '/_authenticated/kas'
    | '/_authenticated/kejadian'
    | '/_authenticated/notulen'
    | '/_authenticated/pengaturan'
    | '/_authenticated/persetujuan'
    | '/_authenticated/peta'
    | '/_authenticated/piket'
    | '/_authenticated/profil'
    | '/_authenticated/roles'
    | '/_authenticated/screening'
    | '/api/auth'
    | '/api/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DaftarRoute: typeof DaftarRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiHealthRoute: typeof ApiHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/screening': {
      id: '/_authenticated/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof AuthenticatedScreeningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/piket': {
      id: '/_authenticated/piket'
      path: '/piket'
      fullPath: '/piket'
      preLoaderRoute: typeof AuthenticatedPiketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/peta': {
      id: '/_authenticated/peta'
      path: '/peta'
      fullPath: '/peta'
      preLoaderRoute: typeof AuthenticatedPetaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/persetujuan': {
      id: '/_authenticated/persetujuan'
      path: '/persetujuan'
      fullPath: '/persetujuan'
      preLoaderRoute: typeof AuthenticatedPersetujuanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pengaturan': {
      id: '/_authenticated/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AuthenticatedPengaturanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notulen': {
      id: '/_authenticated/notulen'
      path: '/notulen'
      fullPath: '/notulen'
      preLoaderRoute: typeof AuthenticatedNotulenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kejadian': {
      id: '/_authenticated/kejadian'
      path: '/kejadian'
      fullPath: '/kejadian'
      preLoaderRoute: typeof AuthenticatedKejadianRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kas': {
      id: '/_authenticated/kas'
      path: '/kas'
      fullPath: '/kas'
      preLoaderRoute: typeof AuthenticatedKasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kaderisasi': {
      id: '/_authenticated/kaderisasi'
      path: '/kaderisasi'
      fullPath: '/kaderisasi'
      preLoaderRoute: typeof AuthenticatedKaderisasiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventaris': {
      id: '/_authenticated/inventaris'
      path: '/inventaris'
      fullPath: '/inventaris'
      preLoaderRoute: typeof AuthenticatedInventarisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etik': {
      id: '/_authenticated/etik'
      path: '/etik'
      fullPath: '/etik'
      preLoaderRoute: typeof AuthenticatedEtikRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anggota': {
      id: '/_authenticated/anggota'
      path: '/anggota'
      fullPath: '/anggota'
      preLoaderRoute: typeof AuthenticatedAnggotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity-log': {
      id: '/_authenticated/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof AuthenticatedActivityLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityLogRoute: typeof AuthenticatedActivityLogRoute
  AuthenticatedAnggotaRoute: typeof AuthenticatedAnggotaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEtikRoute: typeof AuthenticatedEtikRoute
  AuthenticatedInventarisRoute: typeof AuthenticatedInventarisRoute
  AuthenticatedKaderisasiRoute: typeof AuthenticatedKaderisasiRoute
  AuthenticatedKasRoute: typeof AuthenticatedKasRoute
  AuthenticatedKejadianRoute: typeof AuthenticatedKejadianRoute
  AuthenticatedNotulenRoute: typeof AuthenticatedNotulenRoute
  AuthenticatedPengaturanRoute: typeof AuthenticatedPengaturanRoute
  AuthenticatedPersetujuanRoute: typeof AuthenticatedPersetujuanRoute
  AuthenticatedPetaRoute: typeof AuthenticatedPetaRoute
  AuthenticatedPiketRoute: typeof AuthenticatedPiketRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedScreeningRoute: typeof AuthenticatedScreeningRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityLogRoute: AuthenticatedActivityLogRoute,
  AuthenticatedAnggotaRoute: AuthenticatedAnggotaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEtikRoute: AuthenticatedEtikRoute,
  AuthenticatedInventarisRoute: AuthenticatedInventarisRoute,
  AuthenticatedKaderisasiRoute: AuthenticatedKaderisasiRoute,
  AuthenticatedKasRoute: AuthenticatedKasRoute,
  AuthenticatedKejadianRoute: AuthenticatedKejadianRoute,
  AuthenticatedNotulenRoute: AuthenticatedNotulenRoute,
  AuthenticatedPengaturanRoute: AuthenticatedPengaturanRoute,
  AuthenticatedPersetujuanRoute: AuthenticatedPersetujuanRoute,
  AuthenticatedPetaRoute: AuthenticatedPetaRoute,
  AuthenticatedPiketRoute: AuthenticatedPiketRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedScreeningRoute: AuthenticatedScreeningRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DaftarRoute: DaftarRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiHealthRoute: ApiHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
